dist: xenial
language: node_js
cache:
  directories:
    - ~/.yarn
    - ~/.gradle
before_script:
  # make sure we have gradle in ~/.gradle
  - travis_wait test/project/without-plugin/gradlew -v
script:
  - yarn build
  - yarn test
jobs:
  include:
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
